project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  search: true
  page-footer:
    center:
      - text: "@Suzette Flantua 2026"
  title: "Suzette Flantua"



  # Custom header for top navigation
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "My Projects"
        menu:
          - text: "Overview of projects"
            href: projects/index.qmd
          - text: "PPF-Alpine"
            href: projects/PPF-ALPINE/index.qmd
          - text: "Global Human Impact"
            href: projects/GLOBAL-HUMAN-IMPACT/index.qmd
          - text: "Pantropical Dynamics"
            href: projects/PANTROPICAL/index.qmd
          - text: "Latin American Pollen Database"
            href: projects/LAPD/index.qmd
          - text: "Fossilpol"
            href: projects/FOSSILPOL/index.qmd
      - text: "My Publications"
        menu:
          - text: "List of publications"
            href: about_me/list_of_publications.qmd
          - text: "CV"
            href: about_me/cv.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "Get in touch"
        href: collaborate.qmd


format:
  html:
    theme: darkly
    css: styles.css
    toc: true
